# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField()),
                ('blurb', models.CharField(blank=True, default='', max_length=512)),
                ('intro', models.TextField(default='')),
                ('sample_photo', models.URLField(blank=True, default='http://via.placeholder.com/350x150')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('G', 'Giant')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('photo', models.URLField(blank=True, default='http://via.placeholder.com/350x150')),
            ],
        ),
        migrations.CreateModel(
            name='DogBreedRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_relations', to='newshound.Breed')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_relations', to='newshound.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('dogs_mentioned', models.ManyToManyField(blank=True, related_name='posts', to='newshound.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='breeds',
            field=models.ManyToManyField(blank=True, related_name='dogs', through='newshound.DogBreedRelationship', to='newshound.Breed'),
        ),
        migrations.AddField(
            model_name='breed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newshound.BreedGroup'),
        ),
    ]
