# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newshound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newshound.BreedGroup'),
        ),
        migrations.AlterField(
            model_name='breedgroup',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
