# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshound', '0002_auto_20170811_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
