# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newshound', '0003_auto_20170811_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='publication_status',
            field=models.CharField(choices=[('D', 'Draft'), ('E', 'Edit'), ('P', 'Published')], default='D', max_length=1),
        ),
    ]
