# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshound', '0004_auto_20170811_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_good',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
    ]
