# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newshound', '0005_auto_20170811_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='newshound.BreedGroup'),
        ),
    ]
